/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JSP_JNI_in_JSP */

#ifndef _Included_test_JSP_JNI_in_JSP
#define _Included_test_JSP_JNI_in_JSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JSP_JNI_in_JSP
 * Method:    request
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_1JSP_JNI_1in_1JSP_request
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
