/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_spring_JNI_in_Spring */

#ifndef _Included_com_jni_spring_JNI_in_Spring
#define _Included_com_jni_spring_JNI_in_Spring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_spring_JNI_in_Spring
 * Method:    request
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_spring_JNI_1in_1Spring_request
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
